---
- name: Gather facts
  openshift_facts:
    role: common

- name: Set client binary var
  set_fact:
    client_binary: "{{ openshift.common.client_binary |
                        default(openshift_client_binary) }}"

- name: use the default project
  shell: "{{ client_binary }} project default"

- name: Count the infrastructure nodes
  shell: "{{ client_binary }}  get nodes --show-labels | grep role=infra -c"
  register: nodes
  when: node_type == "infra"

- name: Scale the router
  shell: "{{ client_binary }} scale dc/router --replicas={{ nodes.stdout }}"
  when: node_type == "infra"
