---
# NOTE(vponomar): here we use 2 different sources of IP addresses:
# 1) hostvars[item].guest.net exists for old nodes, that haven't been created
#    with this playbook run. Such nodes have detailed info in hostvars.
# 2) hostvars[item].ansible_ssh_host is always correct IP address for newly
#    created nodes. For such nodes we pick it when variant 1 does not work.
- name: Save matched hosts to temporary var
  set_fact:
    current_cluster_hosts: "{{
      current_cluster_hosts | default([]) | union([{
          'name_short': hostvars[item].inventory_hostname_short,
          'name': hostvars[item].inventory_hostname,
          'net': (hostvars[item].guest | default({})).net | default(
              [{'network': vm_network,
                'ipaddress': [hostvars[item].ansible_ssh_host]}])
      }]) }}"
  with_items: "{{ groups.all | select('match', ocp_hostname_prefix) | list }}"

- name: Delete old left-overs if exist in /etc/hosts
  lineinfile:
    dest: '/etc/hosts'
    regexp: '{{ item.name_short }}'
    state: absent
  with_items: "{{ current_cluster_hosts }}"

- name: Gather current cluster IP addresses
  set_fact:
    current_cluster_ips: "{{
      current_cluster_ips | default({}) | combine({
          (item.1.ipaddress | ipv4 | first): [item.0.name_short, item.0.name]
      }) }}"
  with_subelements: ["{{ current_cluster_hosts }}", net]
  when: "item.1.network == vm_network"

- name: Add domain name mapping of newly created cluster nodes to /etc/hosts
  lineinfile:
    dest: '/etc/hosts'
    line: '{{ item.key }} {{ item.value.0 }} {{ item.value.1 }}'
  with_dict: "{{ current_cluster_ips }}"
