---
- name: Import RHSM role
  import_role:
    name: rhsm

- name: Create additional repo with downstream packages for OpenShift 3.X
  block:
  - command: "subscription-manager repos --disable=rhel-7-server-ose-3.{{
              openshift_vers.split('_')[-1] }}-rpms"
  - yum_repository:
      name: "downstream-rhel-7-server-ose-3.{{ openshift_vers.split('_')[-1] }}-rpms"
      baseurl: "{{ ose_puddle_repo }}"
      description: "Downstream repo with development versions of packages for OpenShift"
      enabled: "{{ (ose_puddle_repo != '') | ternary('yes', 'no') }}"
      gpgcheck: "no"
      sslverify: "no"
      cost: 900
  when: ose_puddle_repo != ''
