---
- name: Clear yum cache
  command: "yum clean all"
  ignore_errors: true

- name: Install required common rpms
  package:
    name: "{{ item }}"
    state: latest
  with_items:
  - 'iptables'
  - 'iptables-services'

- name: Enable Gluster 3 repo 
  import_role:
    name: enable-gluster-repo

- name: Install required Gluster 3 rpms
  package:
    name: "{{ item }}"
    state: latest
  with_items:
  - 'redhat-storage-server'
  - 'heketi-client'

- name: Stop firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Start Glusterd and iptables
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
  - iptables
  - glusterd
