---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars_files:
  - vars/main.yaml
  roles:
  - create-vm-add-prod-ose
  - setup-custom-domain-names-for-ansible-runner

- hosts: new_nodes
  gather_facts: yes
  become: no
  vars_files:
  - vars/main.yaml
  roles:
  - setup-custom-domain-names
  - instance-groups
  - package-repos
  - vmware-guest-setup
  - cloud-provider-setup
  - docker-storage-setup
  - openshift-volume-quota

- include: add-node-prerequisite.yaml
  when: openshift_vers in ['v3_6', 'v3_7']

- include: "{{ (openshift_vers in ['v3_6', 'v3_7']) | ternary(
      'noop.yaml',
      lookup('env', 'VIRTUAL_ENV') +
          '/usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml'
  ) }} hosts=new_nodes vars_files=vars/main.yaml"
  when: openshift_vers not in ['v3_6', 'v3_7']

- include: "{{ (openshift_vers in ['v3_6', 'v3_7']) | ternary(
      'noop.yaml',
      lookup('env', 'VIRTUAL_ENV') +
          '/usr/share/ansible/openshift-ansible/playbooks/init/main.yml'
  ) }} hosts=new_nodes"
  when: openshift_vers not in ['v3_6', 'v3_7']

- name: Map domain names and IP addresses of old and new nodes to each other
  hosts: loadbalancer, master, infra, app, cns, crs, !new_nodes
  vars_files:
    - vars/main.yaml
  roles:
    - setup-custom-domain-names

- include: node-setup.yaml

- hosts: loadbalancer, master, infra
  gather_facts: yes
  become: no
  vars_files:
  - vars/main.yaml
  roles:
  - haproxy-server-config

- hosts: single_master
  gather_facts: yes
  become: yes
  vars_files:
  - vars/main.yaml
  roles:
  - ../../../roles/router-scaleup
