---
- hosts: localhost
  ignore_errors: yes
  vars_files:
    - vars/main.yaml
  roles:
    - instance-groups

- hosts: allnodes
  ignore_errors: yes
  vars_files:
    - vars/main.yaml
  roles:
    - rhsm-unregister

- hosts: localhost
  user: root
  become: false
  ignore_errors: yes
  vars_files:
    - vars/main.yaml
  tasks:
    - name: Delete all added VMs
      vmware_guest:
        hostname: "{{ vcenter_host }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        name: "{{ hostvars[item].inventory_hostname }}"
        datacenter: "{{ vcenter_datacenter }}"
        cluster: "{{ vcenter_cluster }}"
        resource_pool: "{{ vcenter_resource_pool }}"
        folder: "/{{ vcenter_datacenter }}/vm/{{ vcenter_folder }}"
        state: absent
        force: true
      with_items: "{{ groups['allnodes'] }}"
    - name: Update /etc/hosts file on Ansible runner machine
      lineinfile:
        path: "/etc/hosts"
        state: absent
        regexp: ".*{{ hostvars[item].inventory_hostname }}.*"
      with_items: "{{ groups['allnodes'] }}"
