---
- hosts: crs
  tasks:
  - name: Install required kernel modules on CRS nodes
    import_role:
      name: openshift_storage_glusterfs
      tasks_from: kernel_modules.yml

- hosts: single_master
  tasks:
  - name: Enable Gluster 3 repo
    import_role:
      name: enable-gluster-repo
  - name: Install and run heketi
    import_role:
      name: heketi-install
  - name: Perform actions on master node which are required to install CRS 
    import_role:
      name: openshift_storage_glusterfs
    vars:
      openshift_storage_glusterfs_name: 'crs'
      openshift_storage_glusterfs_namespace: 'crs'
      openshift_storage_glusterfs_is_native: false
      openshift_storage_glusterfs_heketi_is_native: false
      openshift_storage_glusterfs_heketi_url: "{{ ansible_default_ipv4.address }}"
      openshift_storage_glusterfs_heketi_admin_key: "{{
          (heketi_admin_key.strip() != '') |
              ternary(heketi_admin_key.strip(), omit) }}"
      openshift_storage_glusterfs_heketi_user_key: "{{
          (heketi_user_key.strip() != '') |
              ternary(heketi_user_key.strip(), omit) }}"
      openshift_storage_glusterfs_storageclass: true
      openshift_storage_glusterfs_version: 'latest'
      openshift_storage_glusterfs_block_version: 'latest'
      openshift_storage_glusterfs_block_host_vol_size: "{{
          container_storage_disks.split(',') | map('int') | list | max }}"
      openshift_storage_glusterfs_s3_deploy: false
      openshift_storage_glusterfs_heketi_executor: ssh
