---
- hosts: crs
  gather_facts: yes
  become: no
  vars_files:
  - vars/main.yaml
  roles:
  - setup-custom-domain-names
  - instance-groups
  - package-repos
  - vmware-guest-setup
  - gluster-crs-prerequisites
  - gluster-ports

- name: Map domain names and IP addresses of old and new nodes to each other
  hosts: loadbalancer, master, infra, app, cns
  vars_files:
    - vars/main.yaml
  roles:
    - setup-custom-domain-names
