---
- include: "{{
      lookup('env', 'VIRTUAL_ENV')
  }}/usr/share/ansible/openshift-ansible/playbooks/{{
      (openshift_vers in ['v3_6', 'v3_7']) | ternary('byo', '')
  }}/openshift-node/scaleup.yml"
  vars:
    debug_level: 2
    openshift_debug_level: "{{ debug_level }}"
    openshift_node_debug_level: "{{ node_debug_level | default(debug_level, true) }}"
    openshift_disable_check: docker_image_availability
    osm_controller_args:
    osm_api_server_args:
    openshift_node_kubelet_args:
      cloud-provider:
      - "vsphere"
      cloud-config:
      - "/etc/origin/cloudprovider/vsphere.conf"
      node-labels:
      - "role={{ openshift_node_labels.role }}"
    openshift_master_debug_level: "{{ master_debug_level | default(debug_level, true) }}"
    openshift_master_access_token_max_seconds: 2419200
    openshift_master_api_port: "{{ console_port }}"
    openshift_master_console_port: "{{ console_port }}"
    osm_cluster_network_cidr: 172.16.0.0/16
    openshift_registry_selector: "role=app"
    openshift_router_selector: "role=app"
    openshift_node_local_quota_per_fsgroup: 512Mi
    openshift_master_cluster_method: native
    openshift_cloudprovider_kind: vsphere
    openshift_cloudprovider_vsphere_host: "{{ vcenter_host }}"
    openshift_cloudprovider_vsphere_username: "{{ vcenter_username }}"
    openshift_cloudprovider_vsphere_password: "{{ vcenter_password }}"
    openshift_cloudprovider_vsphere_datacenter: "{{ vcenter_datacenter }}"
    openshift_cloudprovider_vsphere_datastore: "{{ vcenter_datastore }}"
    openshift_cloudprovider_vsphere_folder: "{{ vcenter_folder }}"
    os_sdn_network_plugin_name: "{{ openshift_sdn }}"
    deployment_type: "{{ deployment_type }}"
    load_balancer_hostname: "{{ lb_host }}"
    openshift_master_cluster_hostname: "{{ load_balancer_hostname }}"
    openshift_master_cluster_public_hostname: "{{ load_balancer_hostname }}"
