---
- hosts: localhost
  gather_facts: yes
  ignore_errors: yes
  vars_files:
  - vars/main.yaml
  roles:
  # Group systems
  - instance-groups

- include: prerequisite.yaml

- name: call openshift includes for installer
  include: "{{ lookup('env', 'VIRTUAL_ENV') }}/usr/share/ansible/openshift-ansible/playbooks/byo/config.yml"
  vars:
    openshift_release: "v3.{{ openshift_vers.split('_')[-1] }}"
    debug_level: 2
    console_port: 8443
    openshift_debug_level: "{{ debug_level }}"
    openshift_node_debug_level: "{{ node_debug_level | default(debug_level, true) }}"
    # NOTE(vponomar): following two can be changed to "true" when
    # https://github.com/openshift/openshift-ansible/issues/6086 is fixed
    openshift_enable_service_catalog: false
    template_service_broker_install: false
    osm_controller_args:
      cloud-provider:
      - "vsphere"
      cloud-config:
      - "/etc/origin/cloudprovider/vsphere.conf"
    osm_api_server_args:
      cloud-provider:
      - "vsphere"
      cloud-config:
      - "/etc/origin/cloudprovider/vsphere.conf"
    openshift_node_kubelet_args:
      cloud-provider:
      - "vsphere"
      cloud-config:
      - "/etc/origin/cloudprovider/vsphere.conf"
      node-labels:
      - "role={{ openshift_node_labels.role }}"
    openshift_master_debug_level: "{{ master_debug_level | default(debug_level, true) }}"
    openshift_master_access_token_max_seconds: 2419200
    openshift_hosted_router_replicas: 1
    openshift_hosted_registry_replicas: 1
    openshift_master_api_port: "{{ console_port }}"
    openshift_master_console_port: "{{ console_port }}"
    openshift_master_logging_public_url: "https://kibana.{{ osm_default_subdomain }}"
    openshift_node_local_quota_per_fsgroup: 512Mi
    osm_cluster_network_cidr: 172.16.0.0/16
    osm_use_cockpit: false
    osm_default_node_selector: "role=app"
    openshift_registry_selector: "role=app"
    openshift_override_hostname_check: true
    openshift_router_selector: "role=app"
    openshift_master_cluster_method: native
    openshift_cloudprovider_kind: vsphere
    wildcard_zone: "{{ app_dns_prefix }}.{{ dns_zone }}"
    osm_default_subdomain: "{{ wildcard_zone }}"
    openshift_master_default_subdomain: "{{osm_default_subdomain}}"
    deployment_type: "{{ deployment_type }}"
    load_balancer_hostname: "{{ lb_host }}"
    openshift_master_cluster_hostname: "{{ load_balancer_hostname }}"
    openshift_master_cluster_public_hostname: "{{ load_balancer_hostname }}"
    os_sdn_network_plugin_name: "{{ openshift_sdn }}"
    openshift_master_identity_providers: "[{'name': 'allow_all', 'login': 'true', 'challenge': 'true', 'kind': 'AllowAllPasswordIdentityProvider'}]"
